# ----
# Site

title: Code for YOKOHAMA
url: "https://code4yokohama.github.io"
baseurl: "."
google_analytics_key: UA-59974413-3
google_maps_javascript_api_key:
disqus_shortname:
repository: Code4Yokohama/code4yokohama.github.io

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: App marketing template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Frisco Template
  links:
    - https://github.com/CloudCannon/frisco-jekyll-template

# -----
# Build

timezone: Asia/Tokyo

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  staff_members:
    _hide_content: true
    _icon: account_circle
  projects:
    output: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category_archive
    tag: tag_archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

defaults:
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 440
          height: 440
          uploads_dir: "/images/staff_members"
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
          uploads_dir: "/images/post_uploads"
        content:
          width: 1500
          height: 2000
          uploads_dir: "/images/post_uploads"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
      top_image: "/images/logo/circlelogo.png"
      image: "/images/bgimages/bg004.jpg"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
          uploads_dir: "/images/project_uploads"
        content:
          width: 1500
          height: 2000
          uploads_dir: "/images/project_uploads"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person

# ---- fixed github metadata authentication bug ----
# github : [metadata]
